### PR TITLE
Checking if Class has CarrierWave loaded

### PR DESCRIPTION
**Pull request by basex**
Although I had Carrierwave loaded I was not using it on the class I was trying to pluck_all:
NoMethodError: undefined method `uploaders' for #<Class:0x007f95db547838>

### CODE REVIEW

**Comment by khiav223577** [comment]
Thanks. 
Which version of CarrierWave are you using?

**Comment by khiav223577** [comment]
I test it on my project, all classes inheriting from ActiveRecord::Base do not raise an error.
Could you give more hints about how to trigger this bug?

**Comment by basex** [comment]
I was testing the pluck_all with a project that have Carrierwave 0.10 and Activerecord 5.0.1. The project is using Sinatra, not Rails. The class inherits from ActiveRecord::Base but does not have Carrierwave loaded.

**Comment by khiav223577** [comment]
I just figured it out:

Because of this line in `carrierwave`: 
> elsif defined?(Rails)
https://github.com/carrierwaveuploader/carrierwave/blob/c45699c318ca895f89fa3304204e48b5f1c411f1/lib/carrierwave.rb#L37

The activerecord orm extension of `carrierwave` is not loaded in your sinatra project.
> require 'carrierwave/orm/activerecord'
https://github.com/carrierwaveuploader/carrierwave/blob/c45699c318ca895f89fa3304204e48b5f1c411f1/lib/carrierwave.rb#L48

**Pull request merged**
